"""add outcome to audit_events

Revision ID: 4ce2babc9931
Revises: d420aa223a1d
Create Date: 2026-07-25 00:10:49.234758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ce2babc9931'
down_revision: Union[str, Sequence[str], None] = 'd420aa223a1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand (not autogenerated) so this is safe to
    # apply against a table that already has rows, not just a fresh one.
    op.add_column(
        'audit_events', sa.Column('outcome', sa.String(length=20), nullable=False, server_default='success')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_events', 'outcome')
    # ### end Alembic commands ###
