"""Shared export envelope builders (Milestone 7).

Both `markdown_renderer` and `json_renderer` render the *same* envelope
dict -- built once here from a `QueryResponse`/`ExecutionDetailOut`
(+`WorkflowReportOut`)-shaped dict, whichever API endpoint already
returned to the caller. Nothing here re-derives an answer, a report, a
finding, or a citation -- only reformats what the API already computed.
Never includes API keys, raw prompts, or stack traces.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

PLATFORM_DISCLAIMER = (
    "Northstar Lending Corporation is a fictional company. This document was generated by the "
    "Northstar Enterprise AI Transformation Platform for portfolio demonstration purposes only -- "
    "it is not investment, legal, compliance, or production guidance."
)


def _generated_at() -> str:
    return datetime.now(timezone.utc).isoformat()


def build_query_export_envelope(query_response: dict[str, Any]) -> dict[str, Any]:
    return {
        "title": "Grounded Query Answer",
        "generated_at": _generated_at(),
        "question": query_response["question"],
        "sufficient_context": query_response["sufficient_context"],
        "answer": query_response["answer"],
        "routing": query_response.get("routing"),
        "citations": query_response.get("citations", []),
        "warnings": query_response.get("warnings", []),
        "conflicts": query_response.get("conflicts", []),
        "disclaimer": PLATFORM_DISCLAIMER,
    }


def build_workflow_report_export_envelope(
    report: dict[str, Any], execution: dict[str, Any],
) -> dict[str, Any]:
    return {
        "title": f"{execution['workflow_id']} -- Final Report",
        "generated_at": _generated_at(),
        "execution_id": execution["execution_id"],
        "workflow_id": execution["workflow_id"],
        "status": execution["status"],
        "sections": report["sections"],
        "findings": execution.get("findings", []),
        "evidence_gaps": execution.get("evidence_gaps", []),
        "conflicts": execution.get("conflicts", []),
        "citations": execution.get("citations", []),
        "disclaimer": PLATFORM_DISCLAIMER,
    }
